# Site settings
title: Ivan A. David
twitter_username: ivandavidv
name: Ivan A. David-Venegas

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: StackOverflow
   url: http://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Java
 - Spring Boot
 - Microservices
 - JPA
 - API design
 - SQL
 - Spring MVC
 - REST
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: SENNOVA/GESICOM Researcher
   start: 2019
   end: Ongoing
   employer: SENA
   description: R&D for "Generation of technological strategies for the rational use of antibiotics"; government public info. available <a href="https://www.funcionpublica.gov.co/web/sigep/hdv/-/directorio/M3251875-0347-5/view">here</a>
 - title: Director of the Computer Science academic program
   start: 2018
   end: 2019
   employer: University of Ibague
   description: Responible of the design and delivery of high quality learning opportunities for students on the Computer Science program and courses offered as service to the Engineering faculty.
 - title: Senior Engineer
   start: 2015
   end: 2017
   employer: Zemoga
   description: Working as a senior engineer, I worked closely with international clients specialized on financial advisory services, I was involved in several aspects of the technology including the back-end services.
 - title: Computer Science academic program assistant professor
   start: 2009
   end: 2015
   employer: University of Ibague
   description: HERE COMES DESCRIPTION
- title: Computer Science academic program assistant professor
   start: 2007
   end: 2009
   employer: EAN University
   description: HERE COMES DESCRIPTION
- title: Member Technical Staff
   start: 2005
   end: 2007
   employer: Commoca, Inc.
   description: HERE COMES DESCRIPTION

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1999
   school: University of District Francisco Jose de Caldas, Bogota, Colombia
